name: Deployment to GitHub Pages

on:
  push:
    branches:
      - master  # <-- specify the branch you want to deploy from
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.125.5'
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: hugo --minify --baseURL https://tgb-seq.github.io

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/master' }} # <-- specify same branch as above here
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
d